### ISSUE TITLE
Support for Linux shell

### ISSUE THREAD

**Issue by duarte-pompeu** [NetLogo/Shell-Extension#1]
Is there support for _bash_ or _sh_ in Linux? I couldn't find any info about it.

**Comment by SethTisue** [comment]
yes, I believe it should work on Linux. I don't know why the readme only says "Mac OS X" instead of "Mac OS X and Linux".

**Comment by duarte-pompeu** [comment]
Thanks for the reply. I was trying with the command center - I guess it didn't load the extension.

 I'm still unable to use arguments, though.

```
# works
to exec
  show shell:exec "ls"
end

# fails
to exec
  show shell:exec "ls -a"
end
```

**Comment by SethTisue** [comment]
do `(shell:exec "ls" "-a")`

**Comment by duarte-pompeu** [comment]
Yes, that works! Thank you for your help :)

On 03/11/2016 10:09 PM, Seth Tisue wrote:
(shell:exec "ls" "-a")
