### ISSUE TITLE
How to connect to shell by Emacs

### ISSUE THREAD

**Issue by ofenerci** [NetLogo/Shell-Extension#4]
Hello,
I wonder it is possible to use Emacs and connect to shell by REPL.

**Comment by LaCuneta** [comment]
Hello, thanks for the interest in NetLogo!  

The Shell-Extension isn't an interactive shell for running NetLogo - it doesn't let you use NetLogo code as a command-line REPL.  The Shell-Extension lets you call out to your local system's shell (bash, cmd) from inside NetLogo code, to do whatever you might need to on your system.  I don't think that it would be helpful for the kinds of things you're talking about wanting to do.

I posted to your thread on the netlogo-users list a more in-depth answer: https://groups.google.com/d/msg/netlogo-users/6htuWppfa84/PP5aTjGPDAAJ
